FROM jetbrains/teamcity-agent:latest

USER root

# Установка Python и pip
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    flake8 \
    && rm -rf /var/lib/apt/lists/*

# Создаем символические ссылки для удобства
RUN ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip

# Возвращаем пользователя по умолчанию
USER buildagent