FROM jetbrains/teamcity-agent:latest

USER root

# Установка Python, pip и sudo
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    flake8 \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# Разрешаем buildagent использовать sudo для docker без пароля
RUN echo "buildagent ALL=(ALL) NOPASSWD: /usr/bin/docker" >> /etc/sudoers

USER buildagent