version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: carsharing
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/carsharing
      DB_HOST: db
      DB_PORT: 5432
      DATABASE: postgres
    ports:
      - "5001:5000"
    depends_on:
      - db

volumes:
  postgres_data: